/*! Janson(http://www.gandancing.com) 2011-2012
 *
 *\file
 *\brief		
 *\details	
 *
 *\author	Janson
 *\version	
 *\date		04Jan12
 *
 *\warning	
 *
 *\history \arg	30Jan12, Janson, Create the file
 *	modify from VxWorks source
 *  Legal Declaration: it is for studying VxWorks only.
 */
#ifndef __TASK_MIPS_LIB_H_
#define __TASK_MIPS_LIB_H_

#ifdef __cplusplus
extern "C" {
#endif

#define _RTypeSize 4
#define KERNEL_TCB_REGS 0xC8

#define KERNEL_TCB_GREG_BASE	(KERNEL_TCB_REGS+2*4+2*_RTypeSize)
#define KERNEL_TCB_GREG_OFFSET(n) (KERNEL_TCB_GREG_BASE + (n)*_RTypeSize)
#define	KERNEL_TCB_SR 		(KERNEL_TCB_REGS + 0*4)
#define	KERNEL_TCB_PC 		(KERNEL_TCB_REGS + 1*4)
#define	KERNEL_TCB_LO		(KERNEL_TCB_REGS + 2*4+0*_RTypeSize)
#define	KERNEL_TCB_HI		(KERNEL_TCB_REGS + 2*4+1*_RTypeSize)
#define	KERNEL_TCB_ZERO		KERNEL_TCB_GREG_OFFSET(0)
#define	KERNEL_TCB_AT		KERNEL_TCB_GREG_OFFSET(1)
#define	KERNEL_TCB_V0		KERNEL_TCB_GREG_OFFSET(2)
#define	KERNEL_TCB_V1		KERNEL_TCB_GREG_OFFSET(3)
#define	KERNEL_TCB_A0		KERNEL_TCB_GREG_OFFSET(4)
#define	KERNEL_TCB_A1		KERNEL_TCB_GREG_OFFSET(5)
#define	KERNEL_TCB_A2		KERNEL_TCB_GREG_OFFSET(6)
#define	KERNEL_TCB_A3		KERNEL_TCB_GREG_OFFSET(7)
#define	KERNEL_TCB_T0		KERNEL_TCB_GREG_OFFSET(8)
#define	KERNEL_TCB_T1		KERNEL_TCB_GREG_OFFSET(9)
#define	KERNEL_TCB_T2		KERNEL_TCB_GREG_OFFSET(10)
#define	KERNEL_TCB_T3		KERNEL_TCB_GREG_OFFSET(11)
#define	KERNEL_TCB_T4		KERNEL_TCB_GREG_OFFSET(12)
#define	KERNEL_TCB_T5		KERNEL_TCB_GREG_OFFSET(13)
#define	KERNEL_TCB_T6		KERNEL_TCB_GREG_OFFSET(14)
#define	KERNEL_TCB_T7		KERNEL_TCB_GREG_OFFSET(15)
#define	KERNEL_TCB_S0		KERNEL_TCB_GREG_OFFSET(16)
#define	KERNEL_TCB_S1		KERNEL_TCB_GREG_OFFSET(17)
#define	KERNEL_TCB_S2		KERNEL_TCB_GREG_OFFSET(18)
#define	KERNEL_TCB_S3		KERNEL_TCB_GREG_OFFSET(19)
#define	KERNEL_TCB_S4		KERNEL_TCB_GREG_OFFSET(20)
#define	KERNEL_TCB_S5		KERNEL_TCB_GREG_OFFSET(21)
#define	KERNEL_TCB_S6		KERNEL_TCB_GREG_OFFSET(22)
#define	KERNEL_TCB_S7		KERNEL_TCB_GREG_OFFSET(23)
#define	KERNEL_TCB_T8		KERNEL_TCB_GREG_OFFSET(24)
#define	KERNEL_TCB_T9		KERNEL_TCB_GREG_OFFSET(25)
#define	KERNEL_TCB_K0		KERNEL_TCB_GREG_OFFSET(26)
#define	KERNEL_TCB_K1		KERNEL_TCB_GREG_OFFSET(27)
#define	KERNEL_TCB_GP		KERNEL_TCB_GREG_OFFSET(28)
#define	KERNEL_TCB_SP		KERNEL_TCB_GREG_OFFSET(29)
#define	KERNEL_TCB_S8		KERNEL_TCB_GREG_OFFSET(30)
#define	KERNEL_TCB_RA		KERNEL_TCB_GREG_OFFSET(31)

#define KERNEL_TCB_STATUS	0x3C
#define KERNEL_TCB_LOCK_CNT 0x50
#define KERNEL_TCB_ENTRY	0x70
#define KERNEL_TCB_ERRNO	0x80

#ifdef __cplusplus
}
#endif

#endif
